apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quizmeup

resources:
  - ../../base

patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: rabbitmq-broker-ingress
  - path: stateful-set-patch.yaml
    target:
      kind: StatefulSet
      name: rabbitmq-broker-stateful-set
  - path: autoscaler-patch.yaml
    target:
      kind: HorizontalPodAutoscaler
      name: rabbitmq-broker-autoscaler
  - target:
      kind: StatefulSet
      name: rabbitmq-broker-stateful-set
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: ConfigMap
      name: rabbitmq-broker-config-map
    patch: |-
      - op: replace
        path: /data/rabbitmq.conf
        value: |
          # Configuration pour environnement local - un seul nœud
          cluster_name = quizmeup-rabbitmq-local
          
          # Désactiver complètement le clustering
          cluster_formation.peer_discovery_backend = rabbit_peer_discovery_classic_config
          
          # Configuration de base
          listeners.tcp.default = 5672
          management.tcp.port = 15672
          management.tcp.ip = 0.0.0.0
          
          # Optimisations pour environnement local
          vm_memory_high_watermark.relative = 0.8
          disk_free_limit.relative = 2.0
          
          # Logs simplifiés
          log.console = true
          log.console.level = info
          log.file = false
