apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq-broker-stateful-set
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: rabbitmq
          env:
            # Configuration pour un seul nœud - pas besoin de clustering
            - name: RABBITMQ_USE_LONGNAME
              value: "false"
            - name: RABBITMQ_NODENAME
              value: "rabbit@localhost"
            # Désactiver la découverte de cluster
            - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
              value: "-rabbit cluster_formation [{peer_discovery_backend,rabbit_peer_discovery_classic_config}]"
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 500Mi
