---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: quizmeup
  name: registry-server-deployment
  labels:
    app.kubernetes.io/name: quizmeup-registry-server
    app.kubernetes.io/component: deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: service
      app.kubernetes.io/name: quizmeup-registry-server
  template:
    metadata:
      labels:
        app.kubernetes.io/component: service
        app.kubernetes.io/name: quizmeup-registry-server
    spec:
      containers:
        - name: registry-server-container
          image: quizmeup/registry-server:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: registry-server-secret
          env:
            - name: SPRING_CONFIG_LOCATION
              value: "classpath:/bootstrap.yml,/config/bootstrap.yml"
          volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: true
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 250m
              memory: 380Mi
          livenessProbe:
            failureThreshold: 3
            httpGet:
              port: 8080
              scheme: HTTP
              path: /actuator/health
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 120
          readinessProbe:
            failureThreshold: 3
            httpGet:
              port: 8080
              scheme: HTTP
              path: /actuator/health
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 120
      volumes:
        - name: config-volume
          configMap:
            name: registry-server-config-map
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}