resources:
  - ../../base
patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: argocd-server-ingress
  - path: certificate-patch.yaml
    target:
      kind: Certificate
      name: argo-cd-tls