---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: quizmeup
  name: actuator-config-map
data:
  actuator.yml: |
    management:
      endpoint:
        env:
          show-values: ALWAYS
        metrics:
          enable: true
      endpoints:
        web:
          exposure:
            include: "*"