---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: quizmeup
  name: application-config-map
data:
  application.yml: |
    spring:
      main:
        allow-bean-definition-overriding: true
      security:
        oauth2:
          resource-server:
            jwt:
              issuer-uri: http://authorization-server.quizmeup.local
          client:
            registration:
              server:
                provider: spring
                client-id: ${QUIZ_ME_UP_CLIENT_SERVER_NAME}
                client-name: ${QUIZ_ME_UP_CLIENT_SERVER_NAME}
                client-secret: ${QUIZ_ME_UP_CLIENT_SERVER_SECRET}
                authorization-grant-type: client_credentials
                scope:
                  - read
                  - write
            provider:
              spring:
                token-uri: http://authorization-server.quizmeup.local/oauth2/token
      cloud:
        openfeign:
          oauth2:
            enabled: true
            clientRegistrationId: ${QUIZ_ME_UP_CLIENT_SERVER_NAME}