---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: quizmeup
  name: application-config-map
data:
  application.yml: |
    spring:
      main:
        allow-bean-definition-overriding: true
      cloud:
        kubernetes:
          discovery:
            enabled: true
            all-namespaces: false
          client:
            namespace: quizmeup
    
    eureka:
      client:
        enabled: false
        register-with-eureka: false
        fetch-registry: false