---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: quizmeup
  name: mongo-config-map
data:
  mongo.yml: |
    spring:
      data:
        mongodb:
          host: mongo-database
          port: 27017
          username: ${QUIZ_ME_UP_MONGO_DATABASE_USERNAME}
          password: ${QUIZ_ME_UP_MONGO_DATABASE_PASSWORD}
          authentication-database: admin
          auto-index-creation: true