---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: configuration-server-secret
  namespace: quizmeup
spec:
  encryptedData:
    QUIZ_ME_UP_ENCRYPT_KEY: AgA/ZhzIeilkUFFv2b7CFQc05Ueqn41pGXwrHRBsNcDU7hbD/LXGC9nFy9Vzj94e5y9OUk6wTfQoG0OiO/gvnC/39HeeMXg8oisUABYQq9itGMhMT7fSqoe4O7qItH6kCuEYSV4yND7l+ecEWfsZ0Yxke9hV25A1U4lquslM2io1OF5brXKZMVvwnOaET5AON3MXDOH6epjsruGJtOH3za6qCSc6VVrXXlhs8vyl9Y8sexMS8fHi/J2I5WF4URDRP/rZu5iIWoB3+COk59pCPMs9FoDARV+ep1BvE3wb5n7rO9Idf9CAMGbyqtYe5cDAbFZC51IPlEqruJFpQrd+gfVR4Rokk600lmfnhXRcOzXYrHIIODjrmLVZtc2JZzSSPlElAeqQi/AgJHqT4KB62ZNSqvVh6/seyCRehzpXQO+3HXiEhF+wZdYoGj7KwuJnvvF3ECHYMpqC2flT6x98ZsqsGm649U+lOyn7jS7pf3dftPwQcLiXPpnIalOemDiYZKVUmrNkSKrYybInPw5uv2y/Dm6kYUoIsnc9+Yoi5Pn8V7TIgKK9H+SQUaq1xkph4pUL35Py9/OgKYaXZkob6cvLfM53NvNIhh6Bev5mK+1h70mk43PzfEN8DibhQFUw2Y4ZQjx2a9rDar83AE6/A8ALn2aLZpdTN9CryMgLzMvpmjV81BBEntVkSkP6FQLbqP1FF76K409o/hV5qkQNQSBFRK/l+eWcFltaOzekpUppanVewtmyffYJF/ppi25w6RM0Hziv3to/a3WArqFPEvgl
  template:
    metadata:
      name: configuration-server-secret
      namespace: quizmeup
    type: Opaque
