# Role avec permissions pour lire les ConfigMaps, Secrets et Services
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: quizmeup
  name: spring-cloud-kubernetes-reader
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch"]

---
# RoleBinding qui lie le ServiceAccount 'default' au Role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: quizmeup
  name: default-spring-cloud-kubernetes-reader
subjects:
  - kind: ServiceAccount
    name: default
    namespace: quizmeup
roleRef:
  kind: Role
  name: spring-cloud-kubernetes-reader
  apiGroup: rbac.authorization.k8s.io