---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: quizmeup
  name: spring-application-config-map
data:
  application.yml: |
    spring:
      main:
        allow-bean-definition-overriding: true