---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-database-persistent-volume-claim
  namespace: quizmeup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi