---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: quizmeup
  name: administration-server-config-map
data:
  application.yml: |
    spring:
      cloud:
        kubernetes:
          config:
            enabled: true
            fail-fast: true
            namespace: quizmeup
            sources:
              - name: application-config-map
                namespace: quizmeup